# Generated by Django 4.2.23 on 2025-06-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessForSaleListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=500)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bussiness_for_sale_listing',
            },
        ),
        migrations.CreateModel(
            name='RightbizListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=500)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rightbiz_listing_table',
            },
        ),
    ]
