# Generated by Django 4.2.23 on 2025-06-16 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessforsalelisting',
            name='scraped_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='businessforsalelisting',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightbizlisting',
            name='scraped_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='rightbizlisting',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessforsalelisting',
            name='business_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rightbizlisting',
            name='business_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
